---
title: "fig4"
output: html_document
date: "2025-03-17"
---

# Create the plot of predictive values and confidente intervales of LMM models
# Explication are in the first code while all the others work the same way


# Rho ~ Elo score
```{r}
library(ggplot2)
library(dplyr)


# Create a sequence between min and max Elo score of LMM models
elo_seq <- seq(min(data_norm$elo, na.rm = TRUE), max(data_norm$elo, na.rm = TRUE), length.out = 100)

# Add sequence of confidence intervals for intercept and Elo score variables fog rho in gains and losses from LMM models
rhog_int <- seq(from = -0.25, to = 0.10, by = 0.05)
rhog_coeff <- seq(from = -0.05, to = 0.05, by = 0.01)
rhog_coeff2 <- seq(from = 0.06, to = 0.10, by = 0.01)

rhol_int <- seq(from = -0.66, to = -0.46, by = 0.05)
rhol_coeff <- seq(from = -0.06, to = -0.01, by = 0.01)
rhol_coeff2 <- seq(from = 0, to = 0.03, by = 0.01)

# Create all combinations with all possible confidence intervals
combinations_rhog <- expand.grid(rhog_int = rhog_int, 
                                 rhog_coeff = rhog_coeff, 
                                 rhog_coeff2 = rhog_coeff2)

# Calculation of prediction values for all combination
rho_g_preds <- apply(combinations_rhog, 1, function(x) {
  rho_int <- x[1]
  coeff1 <- x[2]
  coeff2 <- x[3]
  rho_int + coeff1 * elo_seq + coeff2 * elo_seq^2
})

# Dataframe convertion
df_rhog <- data.frame(elo = rep(elo_seq, nrow(combinations_rhog)),
                      rho_g_pred = unlist(rho_g_preds),
                      rhog_int = rep(combinations_rhog$rhog_int, each = length(elo_seq)),
                      rhog_coeff = rep(combinations_rhog$rhog_coeff, each = length(elo_seq)),
                      rhog_coeff2 = rep(combinations_rhog$rhog_coeff2, each = length(elo_seq)))

df_rhog_long <- df_rhog %>%
  pivot_longer(cols = starts_with("rho_g_pred"), 
               names_to = "step", 
               values_to = "value")



# The same for rho in losses
combinations_rhol <- expand.grid(rhol_int = rhol_int, 
                                 rhol_coeff = rhol_coeff, 
                                 rhol_coeff2 = rhol_coeff2)

rho_l_preds <- apply(combinations_rhol, 1, function(x) {
  rho_int <- x[1]
  coeff1 <- x[2]
  coeff2 <- x[3]
  rho_int + coeff1 * elo_seq + coeff2 * elo_seq^2
})

df_rhol <- data.frame(elo = rep(elo_seq, nrow(combinations_rhol)),
                      rho_l_pred = unlist(rho_l_preds),
                      rhol_int = rep(combinations_rhol$rhol_int, each = length(elo_seq)),
                      rhol_coeff = rep(combinations_rhol$rhol_coeff, each = length(elo_seq)),
                      rhol_coeff2 = rep(combinations_rhol$rhol_coeff2, each = length(elo_seq)))

df_rhol_long <- df_rhol %>%
  pivot_longer(cols = starts_with("rho_l_pred"), 
               names_to = "step", 
               values_to = "value")



# Keep only extreme values for each Elo score values for rho in gains to plot the confidence intervals
df_rhog_long_extreme <- df_rhog_long %>%
  group_by(elo) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_g")

# Keep only extreme values for each Elo score values for rho in losses to plot the confidence intervals
df_rhol_long_extreme <- df_rhol_long %>%
  group_by(elo) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_l")

# Dataframe fusion
df_combined <- bind_rows(df_rhog_long_extreme, df_rhol_long_extreme)



# LMM models to plot the prediction value for rho in function of Elo score
h4 <- lmer(rho_g ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(rho_l ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)

# Coefficients extraction
coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]

# Elo score sequence
elo_seq <- seq(min(data_norm$elo, na.rm = TRUE), max(data_norm$elo, na.rm = TRUE), length.out = 100)

# Predictive values calculation for rho in gains
rho_g_pred <- coefs_g["(Intercept)"] + coefs_g["elo"] * elo_seq + coefs_g["I(elo^2)"] * elo_seq^2
# Predictive values calculation for rho in gains
rho_l_pred <- coefs_l["(Intercept)"] + coefs_l["elo"] * elo_seq + coefs_l["I(elo^2)"] * elo_seq^2


# Dataframe creation predictive values
df_modeles <- data.frame(
  elo = elo_seq,
  rho_g_pred = rho_g_pred,
  rho_l_pred = rho_l_pred 
)

# Plot of predictive values with confiences intervales of LMM models
ggplot() +
  geom_ribbon(data = df_combined, aes(x = elo, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +  
  geom_line(data = df_modeles, aes(x = elo, y = rho_g_pred, linetype = "rho_g"), color = "skyblue", size = 1.2) +  
  geom_line(data = df_modeles, aes(x = elo, y = rho_l_pred, linetype = "rho_l"), color = "orange", size = 1.2) +   
  geom_hline(yintercept = 0, size = 0.7) +
  scale_fill_manual(values = c("Rho_g" = "skyblue", "Rho_l" = "orange")) +
  scale_linetype_manual(values = c("rho_g" = "solid", "rho_l" = "dashed")) +
  labs(title = "",
       x = "Normalized value for Elo score",
       y = expression(rho ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1.12, 1)
```


# Alpha ~ Elo score
```{r}
elo_seq <- seq(min(data_norm$elo, na.rm = TRUE), max(data_norm$elo, na.rm = TRUE), length.out = 100)

alphag_int <- seq(from = -0.15, to = 0.56, by = 0.05)
alphag_coeff <- seq(from = -0.09, to = 0.08, by = 0.01)
alphag_coeff2 <- seq(from = -0.14, to = -0.07, by = 0.01)

alphal_int <- seq(from = -0.81, to = -0.36, by = 0.05)
alphal_coeff <- seq(from = -0.06, to = 0.08, by = 0.01)
alphal_coeff2 <- seq(from = -0.01, to = 0.06, by = 0.01)


combinations_alphag <- expand.grid(alphag_int = alphag_int, 
                                 alphag_coeff = alphag_coeff, 
                                 alphag_coeff2 = alphag_coeff2)


alpha_g_preds <- apply(combinations_alphag, 1, function(x) {
  alpha_int <- x[1]
  coeff1 <- x[2]
  coeff2 <- x[3]
  alpha_int + coeff1 * elo_seq + coeff2 * elo_seq^2
})


df_alphag <- data.frame(elo = rep(elo_seq, nrow(combinations_alphag)),
                      alpha_g_pred = unlist(alpha_g_preds),
                      alphag_int = rep(combinations_alphag$alphag_int, each = length(elo_seq)),
                      alphag_coeff = rep(combinations_alphag$alphag_coeff, each = length(elo_seq)),
                      alphag_coeff2 = rep(combinations_alphag$alphag_coeff2, each = length(elo_seq)))

df_alphag_long <- df_alphag %>%
  pivot_longer(cols = starts_with("alpha_g_pred"), 
               names_to = "step", 
               values_to = "value")



combinations_alphal <- expand.grid(alphal_int = alphal_int, 
                                 alphal_coeff = alphal_coeff, 
                                 alphal_coeff2 = alphal_coeff2)

alpha_l_preds <- apply(combinations_alphal, 1, function(x) {
  alpha_int <- x[1]
  coeff1 <- x[2]
  coeff2 <- x[3]
  alpha_int + coeff1 * elo_seq + coeff2 * elo_seq^2
})

df_alphal <- data.frame(elo = rep(elo_seq, nrow(combinations_alphal)),
                      alpha_l_pred = unlist(alpha_l_preds),
                      alphal_int = rep(combinations_alphal$alphal_int, each = length(elo_seq)),
                      alphal_coeff = rep(combinations_alphal$alphal_coeff, each = length(elo_seq)),
                      alphal_coeff2 = rep(combinations_alphal$alphal_coeff2, each = length(elo_seq)))

df_alphal_long <- df_alphal %>%
  pivot_longer(cols = starts_with("alpha_l_pred"), 
               names_to = "step", 
               values_to = "value")




df_alphag_long_extreme <- df_alphag_long %>%
  group_by(elo) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_g")


df_alphal_long_extreme <- df_alphal_long %>%
  group_by(elo) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_l")


df_combined <- bind_rows(df_alphag_long_extreme, df_alphal_long_extreme)




h4 <- lmer(alpha_g ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(alpha_l ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)


coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]


elo_seq <- seq(min(data_norm$elo, na.rm = TRUE), max(data_norm$elo, na.rm = TRUE), length.out = 100)


alpha_g_pred <- coefs_g["(Intercept)"] + coefs_g["elo"] * elo_seq + coefs_g["I(elo^2)"] * elo_seq^2

alpha_l_pred <- coefs_l["(Intercept)"] + coefs_l["elo"] * elo_seq + coefs_l["I(elo^2)"] * elo_seq^2


df_modeles <- data.frame(
  elo = elo_seq,
  alpha_g_pred = alpha_g_pred,
  alpha_l_pred = alpha_l_pred
)


ggplot() +
  geom_ribbon(data = df_combined, aes(x = elo, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +  
  geom_line(data = df_modeles, aes(x = elo, y = alpha_g_pred, linetype = "alpha_g"), color = "skyblue", size = 1.2) +  
  geom_line(data = df_modeles, aes(x = elo, y = alpha_l_pred, linetype = "alpha_l"), color = "orange", size = 1.2) +   
  geom_hline(yintercept = 0, size = 0.7) +
  scale_fill_manual(values = c("Alpha_g" = "skyblue", "Alpha_l" = "orange")) +
  scale_linetype_manual(values = c("alpha_g" = "solid", "alpha_l" = "dashed")) +
  labs(title = "",
       x = "Normalized value for Elo score",
       y = expression(alpha ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1.12, 1)
```



# Rho ~ Trial number
```{r}
mean_trial_number_seq <- seq(min(data_norm$mean_trial_number, na.rm = TRUE), max(data_norm$mean_trial_number, na.rm = TRUE), length.out = 100)

rhog_int <- seq(from = -0.25, to = 0.10, by = 0.01)
rhog_coeff <- seq(from = -0.21, to = -0.17, by = 0.005)

rhol_int <- seq(from = -0.66, to = -0.46, by = 0.01)
rhol_coeff <- seq(from = 0.01, to = 0.04, by = 0.005)


combinations_rhog <- expand.grid(rhog_int = rhog_int, rhog_coeff = rhog_coeff)


rho_g_preds <- apply(combinations_rhog, 1, function(x) {
  rho_int <- x[1]
  coeff <- x[2]
  rho_int + coeff * mean_trial_number_seq
})


df_rhog <- data.frame(mean_trial_number = rep(mean_trial_number_seq, length(rhog_int) * length(rhog_coeff)),
                      rho_g_pred = unlist(rho_g_preds),
                      rhog_int = rep(combinations_rhog$rhog_int, each = length(mean_trial_number_seq)),
                      rhog_coeff = rep(combinations_rhog$rhog_coeff, each = length(mean_trial_number_seq)))

df_rhog_long <- df_rhog %>%
  pivot_longer(cols = starts_with("rho_g_pred"), 
               names_to = "step", 
               values_to = "value")



combinations_rhol <- expand.grid(rhol_int = rhol_int, rhol_coeff = rhol_coeff)


rho_l_preds <- apply(combinations_rhol, 1, function(x) {
  rho_int <- x[1]
  coeff <- x[2]
  rho_int + coeff * mean_trial_number_seq
})


df_rhol <- data.frame(mean_trial_number = rep(mean_trial_number_seq, length(rhol_int) * length(rhol_coeff)),
                      rho_l_pred = unlist(rho_l_preds),
                      rhol_int = rep(combinations_rhol$rhol_int, each = length(mean_trial_number_seq)),
                      rhol_coeff = rep(combinations_rhol$rhol_coeff, each = length(mean_trial_number_seq)))

df_rhol_long <- df_rhol %>%
  pivot_longer(cols = starts_with("rho_l_pred"), 
               names_to = "step", 
               values_to = "value")



df_rhog_long_extreme <- df_rhog_long %>%
  group_by(mean_trial_number) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_g")


df_rhol_long_extreme <- df_rhol_long %>%
  group_by(mean_trial_number) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_l")


df_combined <- bind_rows(df_rhog_long_extreme, df_rhol_long_extreme)




h4 <- lmer(rho_g ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(rho_l ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)


coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]


mean_trial_number_seq <- seq(min(data_norm$mean_trial_number, na.rm = TRUE), max(data_norm$mean_trial_number, na.rm = TRUE), length.out = 100)

rho_g_pred <- coefs_g["(Intercept)"] + coefs_g["mean_trial_number"] * mean_trial_number_seq

rho_l_pred <- coefs_l["(Intercept)"] + coefs_l["mean_trial_number"] * mean_trial_number_seq



df_modeles <- data.frame(
  mean_trial_number = mean_trial_number_seq,
  rho_g_pred = rho_g_pred,
  rho_l_pred = rho_l_pred
)


ggplot() +
  geom_ribbon(data = df_combined, aes(x = mean_trial_number, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +
  geom_line(data = df_modeles, aes(x = mean_trial_number, y = rho_g_pred, linetype = "rho_g"), color = "skyblue", linewidth = 1.2) +
  geom_line(data = df_modeles, aes(x = mean_trial_number, y = rho_l_pred, linetype = "rho_l"), color = "orange", linewidth = 1.2) +   
  geom_hline(yintercept = 0, linewidth = 0.7) +
  scale_fill_manual(values = c("Rho_g" = "skyblue", "Rho_l" = "orange")) +
  scale_linetype_manual(values = c("rho_g" = "solid", "rho_l" = "solid")) +
  labs(title = "",
       x = "Normalized value for mean trial number",
       y = expression(rho ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1, 1.05)

```



```{r}
mean_trial_number_seq <- seq(min(data_norm$mean_trial_number, na.rm = TRUE), max(data_norm$mean_trial_number, na.rm = TRUE), length.out = 100)

alphag_int <- seq(from = -0.15, to = 0.56, by = 0.01)
alphag_coeff <- seq(from = -0.01, to = 0.07, by = 0.005)

alphal_int <- seq(from = -0.81, to = -0.36, by = 0.01)
alphal_coeff <- seq(from = -0.04, to = 0.03, by = 0.005)


combinations_alphag <- expand.grid(alphag_int = alphag_int, alphag_coeff = alphag_coeff)


alpha_g_preds <- apply(combinations_alphag, 1, function(x) {
  alpha_int <- x[1]
  coeff <- x[2]
  alpha_int + coeff * mean_trial_number_seq
})


df_alphag <- data.frame(mean_trial_number = rep(mean_trial_number_seq, length(alphag_int) * length(alphag_coeff)),
                      alpha_g_pred = unlist(alpha_g_preds),
                      alphag_int = rep(combinations_alphag$alphag_int, each = length(mean_trial_number_seq)),
                      alphag_coeff = rep(combinations_alphag$alphag_coeff, each = length(mean_trial_number_seq)))

df_alphag_long <- df_alphag %>%
  pivot_longer(cols = starts_with("alpha_g_pred"), 
               names_to = "step", 
               values_to = "value")



combinations_alphal <- expand.grid(alphal_int = alphal_int, alphal_coeff = alphal_coeff)


alpha_l_preds <- apply(combinations_alphal, 1, function(x) {
  alpha_int <- x[1]
  coeff <- x[2]
  alpha_int + coeff * mean_trial_number_seq
})


df_alphal <- data.frame(mean_trial_number = rep(mean_trial_number_seq, length(alphal_int) * length(alphal_coeff)),
                      alpha_l_pred = unlist(alpha_l_preds),
                      alphal_int = rep(combinations_alphal$alphal_int, each = length(mean_trial_number_seq)),
                      alphal_coeff = rep(combinations_alphal$alphal_coeff, each = length(mean_trial_number_seq)))

df_alphal_long <- df_alphal %>%
  pivot_longer(cols = starts_with("alpha_l_pred"), 
               names_to = "step", 
               values_to = "value")



df_alphag_long_extreme <- df_alphag_long %>%
  group_by(mean_trial_number) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_g")


df_alphal_long_extreme <- df_alphal_long %>%
  group_by(mean_trial_number) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_l")


df_combined <- bind_rows(df_alphag_long_extreme, df_alphal_long_extreme)



h4 <- lmer(alpha_g ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(alpha_l ~ age_category + sex + elo + I(elo^2) + mean_trial_number + (1|monkey), data = data_norm)

coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]


mean_trial_number_seq <- seq(min(data_norm$mean_trial_number, na.rm = TRUE), max(data_norm$mean_trial_number, na.rm = TRUE), length.out = 100)


alpha_g_pred <- coefs_g["(Intercept)"] + coefs_g["mean_trial_number"] * mean_trial_number_seq

alpha_l_pred <- coefs_l["(Intercept)"] + coefs_l["mean_trial_number"] * mean_trial_number_seq


df_modeles <- data.frame(
  mean_trial_number = mean_trial_number_seq,
  alpha_g_pred = alpha_g_pred,
  alpha_l_pred = alpha_l_pred
)


ggplot() +
  geom_ribbon(data = df_combined, aes(x = mean_trial_number, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +
  geom_line(data = df_modeles, aes(x = mean_trial_number, y = alpha_g_pred, linetype = "alpha_g"), color = "skyblue", size = 1.2) + 
  geom_line(data = df_modeles, aes(x = mean_trial_number, y = alpha_l_pred, linetype = "alpha_l"), color = "orange", size = 1.2) +   
  geom_hline(yintercept = 0, size = 0.7) +
  scale_fill_manual(values = c("Alpha_g" = "skyblue", "Alpha_l" = "orange")) +
  scale_linetype_manual(values = c("alpha_g" = "dashed", "alpha_l" = "dashed")) +
  labs(title = "",
       x = "Normalized value for mean trial number",
       y = expression(alpha ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1, 1)
```


# Rho ~ COP
```{r}
COP_seq <- seq(min(data_norm$COP, na.rm = TRUE), max(data_norm$COP, na.rm = TRUE), length.out = 100)

rhog_int <- seq(from = -0.14, to = 0.20, by = 0.01)
rhog_coeff <- seq(from = 0.02, to = 0.05, by = 0.005)

rhol_int <- seq(from = -0.63, to = -0.46, by = 0.01)
rhol_coeff <- seq(from = 0.01, to = 0.03, by = 0.005)


combinations_rhog <- expand.grid(rhog_int = rhog_int, rhog_coeff = rhog_coeff)


rho_g_preds <- apply(combinations_rhog, 1, function(x) {
  rho_int <- x[1]
  coeff <- x[2]
  rho_int + coeff * COP_seq
})


df_rhog <- data.frame(COP = rep(COP_seq, length(rhog_int) * length(rhog_coeff)),
                      rho_g_pred = unlist(rho_g_preds),
                      rhog_int = rep(combinations_rhog$rhog_int, each = length(COP_seq)),
                      rhog_coeff = rep(combinations_rhog$rhog_coeff, each = length(COP_seq)))

df_rhog_long <- df_rhog %>%
  pivot_longer(cols = starts_with("rho_g_pred"), 
               names_to = "step", 
               values_to = "value")



combinations_rhol <- expand.grid(rhol_int = rhol_int, rhol_coeff = rhol_coeff)


rho_l_preds <- apply(combinations_rhol, 1, function(x) {
  rho_int <- x[1]
  coeff <- x[2]
  rho_int + coeff * COP_seq
})


df_rhol <- data.frame(COP = rep(COP_seq, length(rhol_int) * length(rhol_coeff)),
                      rho_l_pred = unlist(rho_l_preds),
                      rhol_int = rep(combinations_rhol$rhol_int, each = length(COP_seq)),
                      rhol_coeff = rep(combinations_rhol$rhol_coeff, each = length(COP_seq)))

df_rhol_long <- df_rhol %>%
  pivot_longer(cols = starts_with("rho_l_pred"), 
               names_to = "step", 
               values_to = "value")




df_rhog_long_extreme <- df_rhog_long %>%
  group_by(COP) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_g")


df_rhol_long_extreme <- df_rhol_long %>%
  group_by(COP) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_l")


df_combined <- bind_rows(df_rhog_long_extreme, df_rhol_long_extreme)



h4 <- lmer(rho_g ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(rho_l ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)


coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]


COP_seq <- seq(min(data_norm$COP, na.rm = TRUE), max(data_norm$COP, na.rm = TRUE), length.out = 100)

rho_g_pred <- coefs_g["(Intercept)"] + coefs_g["COP"] * COP_seq

rho_l_pred <- coefs_l["(Intercept)"] + coefs_l["COP"] * COP_seq



df_modeles <- data.frame(
  COP = COP_seq,
  rho_g_pred = rho_g_pred,
  rho_l_pred = rho_l_pred
)


ggplot() +
  geom_ribbon(data = df_combined, aes(x = COP, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +
  geom_line(data = df_modeles, aes(x = COP, y = rho_g_pred, linetype = "rho_g"), color = "skyblue", size = 1.2) + 
  geom_line(data = df_modeles, aes(x = COP, y = rho_l_pred, linetype = "rho_l"), color = "orange", size = 1.2) +  
  geom_hline(yintercept = 0, size = 0.7) +
  scale_fill_manual(values = c("Rho_g" = "skyblue", "Rho_l" = "orange")) +
  scale_linetype_manual(values = c("rho_g" = "solid", "rho_l" = "solid")) +
  labs(title = "",
       x = "Normalized value for COP",
       y = expression(rho ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1, 1)

```


# Alpha ~ COP
```{r}
COP_seq <- seq(min(data_norm$COP, na.rm = TRUE), max(data_norm$COP, na.rm = TRUE), length.out = 100)

alphag_int <- seq(from = -0.28, to = 0.39, by = 0.01)
alphag_coeff <- seq(from = -0.07, to = -0.01, by = 0.005)

alphal_int <- seq(from = -0.77, to = -0.34, by = 0.01)
alphal_coeff <- seq(from = -0.02, to = 0.03, by = 0.005)

combinations_alphag <- expand.grid(alphag_int = alphag_int, alphag_coeff = alphag_coeff)


alpha_g_preds <- apply(combinations_alphag, 1, function(x) {
  alpha_int <- x[1]
  coeff <- x[2]
  alpha_int + coeff * COP_seq
})


df_alphag <- data.frame(COP = rep(COP_seq, length(alphag_int) * length(alphag_coeff)),
                      alpha_g_pred = unlist(alpha_g_preds),
                      alphag_int = rep(combinations_alphag$alphag_int, each = length(COP_seq)),
                      alphag_coeff = rep(combinations_alphag$alphag_coeff, each = length(COP_seq)))

df_alphag_long <- df_alphag %>%
  pivot_longer(cols = starts_with("alpha_g_pred"), 
               names_to = "step", 
               values_to = "value")



combinations_alphal <- expand.grid(alphal_int = alphal_int, alphal_coeff = alphal_coeff)


alpha_l_preds <- apply(combinations_alphal, 1, function(x) {
  alpha_int <- x[1]
  coeff <- x[2]
  alpha_int + coeff * COP_seq
})


df_alphal <- data.frame(COP = rep(COP_seq, length(alphal_int) * length(alphal_coeff)),
                      alpha_l_pred = unlist(alpha_l_preds),
                      alphal_int = rep(combinations_alphal$alphal_int, each = length(COP_seq)),
                      alphal_coeff = rep(combinations_alphal$alphal_coeff, each = length(COP_seq)))

df_alphal_long <- df_alphal %>%
  pivot_longer(cols = starts_with("alpha_l_pred"), 
               names_to = "step", 
               values_to = "value")



df_alphag_long_extreme <- df_alphag_long %>%
  group_by(COP) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_g")


df_alphal_long_extreme <- df_alphal_long %>%
  group_by(COP) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_l")

df_combined <- bind_rows(df_alphag_long_extreme, df_alphal_long_extreme)



h4 <- lmer(alpha_g ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(alpha_l ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)

coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]


COP_seq <- seq(min(data_norm$COP, na.rm = TRUE), max(data_norm$COP, na.rm = TRUE), length.out = 100)


alpha_g_pred <- coefs_g["(Intercept)"] + coefs_g["COP"] * COP_seq

alpha_l_pred <- coefs_l["(Intercept)"] + coefs_l["COP"] * COP_seq


df_modeles <- data.frame(
  COP = COP_seq,
  alpha_g_pred = alpha_g_pred,
  alpha_l_pred = alpha_l_pred
)


ggplot() +
  geom_ribbon(data = df_combined, aes(x = COP, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +  
  geom_line(data = df_modeles, aes(x = COP, y = alpha_g_pred, linetype = "alpha_g"), color = "skyblue", size = 1.2) +  
  geom_line(data = df_modeles, aes(x = COP, y = alpha_l_pred, linetype = "alpha_l"), color = "orange", size = 1.2) +  
  geom_hline(yintercept = 0, size = 0.7) +
  scale_fill_manual(values = c("Alpha_g" = "skyblue", "Alpha_l" = "orange")) +
  scale_linetype_manual(values = c("alpha_g" = "solid", "alpha_l" = "dashed")) +
  labs(title = "",
       x = "Normalized value for COP",
       y = expression(alpha ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1, 1)

```


# Rho ~ Certainty
```{r}
certainty_seq <- seq(min(data_norm$certainty, na.rm = TRUE), max(data_norm$certainty, na.rm = TRUE), length.out = 100)

rhog_int <- seq(from = -0.14, to = 0.20, by = 0.01)
rhog_coeff <- seq(from = 0, to = 0.04, by = 0.005)

rhol_int <- seq(from = -0.63, to = -0.46, by = 0.01)
rhol_coeff <- seq(from = -0.01, to = 0.01, by = 0.005)


combinations_rhog <- expand.grid(rhog_int = rhog_int, rhog_coeff = rhog_coeff)


rho_g_preds <- apply(combinations_rhog, 1, function(x) {
  rho_int <- x[1]
  coeff <- x[2]
  rho_int + coeff * certainty_seq
})


df_rhog <- data.frame(certainty = rep(certainty_seq, length(rhog_int) * length(rhog_coeff)),
                      rho_g_pred = unlist(rho_g_preds),
                      rhog_int = rep(combinations_rhog$rhog_int, each = length(certainty_seq)),
                      rhog_coeff = rep(combinations_rhog$rhog_coeff, each = length(certainty_seq)))

df_rhog_long <- df_rhog %>%
  pivot_longer(cols = starts_with("rho_g_pred"), 
               names_to = "step", 
               values_to = "value")



combinations_rhol <- expand.grid(rhol_int = rhol_int, rhol_coeff = rhol_coeff)


rho_l_preds <- apply(combinations_rhol, 1, function(x) {
  rho_int <- x[1]
  coeff <- x[2]
  rho_int + coeff * certainty_seq
})


df_rhol <- data.frame(certainty = rep(certainty_seq, length(rhol_int) * length(rhol_coeff)),
                      rho_l_pred = unlist(rho_l_preds),
                      rhol_int = rep(combinations_rhol$rhol_int, each = length(certainty_seq)),
                      rhol_coeff = rep(combinations_rhol$rhol_coeff, each = length(certainty_seq)))

df_rhol_long <- df_rhol %>%
  pivot_longer(cols = starts_with("rho_l_pred"), 
               names_to = "step", 
               values_to = "value")




df_rhog_long_extreme <- df_rhog_long %>%
  group_by(certainty) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_g")


df_rhol_long_extreme <- df_rhol_long %>%
  group_by(certainty) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Rho_l")


df_combined <- bind_rows(df_rhog_long_extreme, df_rhol_long_extreme)



h4 <- lmer(rho_g ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(rho_l ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)


coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]


COP_seq <- seq(min(data_norm$certainty, na.rm = TRUE), max(data_norm$certainty, na.rm = TRUE), length.out = 100)

rho_g_pred <- coefs_g["(Intercept)"] + coefs_g["certainty"] * certainty_seq

rho_l_pred <- coefs_l["(Intercept)"] + coefs_l["certainty"] * certainty_seq



df_modeles <- data.frame(
  certainty = certainty_seq,
  rho_g_pred = rho_g_pred,
  rho_l_pred = rho_l_pred
)


ggplot() +
  geom_ribbon(data = df_combined, aes(x = certainty, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +
  geom_line(data = df_modeles, aes(x = certainty, y = rho_g_pred, linetype = "rho_g"), color = "skyblue", size = 1.2) + 
  geom_line(data = df_modeles, aes(x = certainty, y = rho_l_pred, linetype = "rho_l"), color = "orange", size = 1.2) +  
  geom_hline(yintercept = 0, size = 0.7) +
  scale_fill_manual(values = c("Rho_g" = "skyblue", "Rho_l" = "orange")) +
  scale_linetype_manual(values = c("rho_g" = "dashed", "rho_l" = "dashed")) +
  labs(title = "",
       x = "Normalized value for Certainty",
       y = expression(rho ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1, 1)

```


# Alpha ~ Certainty
```{r}
certainty_seq <- seq(min(data_norm$certainty, na.rm = TRUE), max(data_norm$certainty, na.rm = TRUE), length.out = 100)

alphag_int <- seq(from = -0.28, to = 0.39, by = 0.01)
alphag_coeff <- seq(from = -0.07, to = -0.01, by = 0.005)

alphal_int <- seq(from = -0.77, to = -0.34, by = 0.01)
alphal_coeff <- seq(from = -0.02, to = 0.03, by = 0.005)

combinations_alphag <- expand.grid(alphag_int = alphag_int, alphag_coeff = alphag_coeff)


alpha_g_preds <- apply(combinations_alphag, 1, function(x) {
  alpha_int <- x[1]
  coeff <- x[2]
  alpha_int + coeff * certainty_seq
})


df_alphag <- data.frame(certainty = rep(certainty_seq, length(alphag_int) * length(alphag_coeff)),
                      alpha_g_pred = unlist(alpha_g_preds),
                      alphag_int = rep(combinations_alphag$alphag_int, each = length(certainty_seq)),
                      alphag_coeff = rep(combinations_alphag$alphag_coeff, each = length(certainty_seq)))

df_alphag_long <- df_alphag %>%
  pivot_longer(cols = starts_with("alpha_g_pred"), 
               names_to = "step", 
               values_to = "value")



combinations_alphal <- expand.grid(alphal_int = alphal_int, alphal_coeff = alphal_coeff)


alpha_l_preds <- apply(combinations_alphal, 1, function(x) {
  alpha_int <- x[1]
  coeff <- x[2]
  alpha_int + coeff * certainty_seq
})


df_alphal <- data.frame(certainty = rep(certainty_seq, length(alphal_int) * length(alphal_coeff)),
                      alpha_l_pred = unlist(alpha_l_preds),
                      alphal_int = rep(combinations_alphal$alphal_int, each = length(certainty_seq)),
                      alphal_coeff = rep(combinations_alphal$alphal_coeff, each = length(certainty_seq)))

df_alphal_long <- df_alphal %>%
  pivot_longer(cols = starts_with("alpha_l_pred"), 
               names_to = "step", 
               values_to = "value")



df_alphag_long_extreme <- df_alphag_long %>%
  group_by(certainty) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_g")


df_alphal_long_extreme <- df_alphal_long %>%
  group_by(certainty) %>%
  summarise(
    ymin = min(value),
    ymax = max(value)
  ) %>%
  mutate(group = "Alpha_l")

df_combined <- bind_rows(df_alphag_long_extreme, df_alphal_long_extreme)



h4 <- lmer(alpha_g ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)
h5 <- lmer(alpha_l ~ age_category + sex + COP + certainty + mean_trial_number + (1|monkey), data = data_norm)

coefs_g <- summary(h4)$coefficients[, "Estimate"]

coefs_l <- summary(h5)$coefficients[, "Estimate"]


certainty_seq <- seq(min(data_norm$certainty, na.rm = TRUE), max(data_norm$certainty, na.rm = TRUE), length.out = 100)


alpha_g_pred <- coefs_g["(Intercept)"] + coefs_g["certainty"] * certainty_seq

alpha_l_pred <- coefs_l["(Intercept)"] + coefs_l["certainty"] * certainty_seq


df_modeles <- data.frame(
  certainty = certainty_seq,
  alpha_g_pred = alpha_g_pred,
  alpha_l_pred = alpha_l_pred
)


ggplot() +
  geom_ribbon(data = df_combined, aes(x = certainty, ymin = ymin, ymax = ymax, fill = group), alpha = 0.3) +  
  geom_line(data = df_modeles, aes(x = certainty, y = alpha_g_pred, linetype = "alpha_g"), color = "skyblue", size = 1.2) +  
  geom_line(data = df_modeles, aes(x = certainty, y = alpha_l_pred, linetype = "alpha_l"), color = "orange", size = 1.2) +  
  geom_hline(yintercept = 0, size = 0.7) +
  scale_fill_manual(values = c("Alpha_g" = "skyblue", "Alpha_l" = "orange")) +
  scale_linetype_manual(values = c("alpha_g" = "dashed", "alpha_l" = "dashed")) +
  labs(title = "",
       x = "Normalized value for Certainty",
       y = expression(alpha ~ " predicted value")) +
  theme_classic(base_size = 14) +
  theme(
    axis.title.x = element_text(size = 36),
    axis.title.y = element_text(size = 36),
    axis.text.x = element_text(size = 30),
    axis.text.y = element_text(size = 30),
    plot.title = element_text(face = "bold", hjust = 0.5, size = 16),
    plot.caption = element_text(size = 10),
    legend.position = "none",
    legend.title = element_blank(),
    plot.margin = margin(1, 1, 1, 1, "cm")
  ) + 
  ylim(-1, 1)

```
